Repository mattruder/rancid-tomatillos, pull requests merged in 2022-05, with the labels that each got.

#6 Display all movies
  src/App.js
  src/MovieCard.css
  src/MovieCard.js
  src/Movies.css
  src/Movies.js
  src/Nav.css
  src/Nav.js
  src/movieData.js
Labels: iteration1

#7 Feature/display single movie
  src/App.js
  src/MovieCard.css
  src/MovieCard.js
  src/MovieDetails.css
  src/MovieDetails.js
  src/Movies.js
  src/Nav.js
Labels: enhancement

#8 Refactor data to come from network requests
  src/App.js
  src/MovieDetails.js
  src/movieData.js
Labels: data, refactor

#10 Add basic CSS. Might refactor later
  src/MovieCard.css
  src/MovieDetails.css
  src/MovieDetails.js
  src/Movies.css
  src/Nav.css
  src/Nav.js
Labels: enhancement

#14 Feature/cypress
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/testing.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/MovieDetails.js
Labels: iteration4, testing

#17 Feature/search filter
  src/App.css
  src/App.js
  src/MovieDetails.css
  src/MovieDetails.js
  src/Nav.js
  src/searchBar.css
  src/searchBar.js
Labels: enhancement, iteration5

#20 Add final Cypress Tests and CSS for navbar
  cypress/integration/testing.js
  src/App.js
  src/MovieCard.css
  src/Nav.css
  src/searchBar.css
  src/searchBar.js
Labels: enhancement, testing

#21 Update README, add images for README
  README.md
  src/images/rancid-tomatillos.png
Labels: documentation
